## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - PROVIDER-INFRA-SETUP
  - STATEFUL-APP-DEPLOY
  - APP-FUNC-TEST
  - APP-CHAOS-TEST
  - CLUSTER-CLEANUP

variables: 
  utils_path: "/openebs/e2e-aws/script/utils"

## Setup the kubernetes cluster

aws-cluster:
  image: atulabhi/kops:v8
  stage: CLUSTER-SETUP 
  script: 
    - ./script/aws
  artifacts:
    paths:
      - aws/

## Setup OpenEBS control plane

openebs-aws-deploy:
  image: atulabhi/kops:v8
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - aws-cluster
  script: 
   - ./script/provider/infra-setup
  artifacts:
    paths:
      - aws-openebs/

## Define a job template for app deployers

.app_deploy_template:
  image: atulabhi/kops:v8
  stage: STATEFUL-APP-DEPLOY 
  dependencies:
    - openebs-aws-deploy
  artifacts:
    paths: 
      - aws-openebs/

## Define the app deployer jobs

        ## PERCONA-JIVA
percona-jiva-run/load/check 0:2:
  extends: .app_deploy_template
  script:
   - ./script/apps/percona/deployer/percona-app-deploy-jiva

percona-jiva-run/load/check 1:2:
  extends: .app_deploy_template
  before_script:
   - sleep 180
  script:
   - ./script/apps/percona/workload/jiva/percona-app-workload-jiva
## PERCONA-JIVA-SINGLE-REPLICA
percona-jiva-single-replica-run/load/check:
  extends: .app_deploy_template
  script:
   - ./script/apps/percona/deployer/percona-deploy-jiva-single-replica

     # PERCONA-CSTOR
percona-cstor-run/load/check 0:2:
  extends: .app_deploy_template
  script: 
   - ./script/apps/percona/deployer/percona-app-deploy-cstor

percona-cstor-run/load/check 1:2:
  extends: .app_deploy_template
  before_script: 
   - sleep 180
  script: 
   - ./script/apps/percona/workload/cstor/percona-app-workload-cstor


.func_test_template:
  image: atulabhi/kops:v8
  stage: APP-FUNC-TEST
  when: always 
  artifacts:
    paths: 
      - aws-openebs/


k8s-snapshot-clone-creation-{snapshot-clone-jiva}:
  extends: .func_test_template
  script:
   - ./script/apps/percona/functional/jiva/k8s-snapshot-clone


## Define job template for chaos jobs 

.chaos_test_template:
  image: atulabhi/kops:v8
  stage: APP-CHAOS-TEST
  when: always 
  artifacts:
    paths: 
      - aws-openebs/


single-repl-kill-{percona-jiva-single-replica}:
  extends: .chaos_test_template #dependencies: percona-jiva
  script:
   - ./script/apps/percona/chaos/jiva/single-replica-failure


cleanup-aws:
  when: always
  image: atulabhi/kops:v8
  dependencies:
    - aws-cluster
  stage: CLUSTER-CLEANUP
  script: 
    - chmod 755 ./script/aws-cleanup
    - ./script/aws-cleanup
