## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - PROVIDER-INFRA-SETUP
  - STATEFUL-APP-DEPLOY
  - NODE-DRAIN
  - CLUSTER-CLEANUP

variables: 
  utils_path: "/openebs/e2e-aws/script/utils"

## Setup the kubernetes cluster

aws-cluster:
  image: atulabhi/kops:v8
  stage: CLUSTER-SETUP 
  script: 
    - ./script/aws
  artifacts:
    paths:
      - aws/

## Setup OpenEBS control plane

openebs-aws-deploy:
  image: atulabhi/kops:v8
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - aws-cluster
  script: 
   - ./script/provider/infra-setup
  artifacts:
    paths:
      - aws-openebs/

## Define a job template for app deployers

.app_deploy_template:
  image: atulabhi/kops:v8
  stage: STATEFUL-APP-DEPLOY 
  dependencies:
    - openebs-aws-deploy
  artifacts:
    paths: 
      - aws-openebs/

## Define the app deployer jobs

# PERCONA-CSTOR
percona-cstor-run/load/check 0:3:
  extends: .app_deploy_template
  script: 
   - ./script/apps/percona/deployer/percona-app-deploy-cstor

percona-cstor-run/load/check 1:3:
  extends: .app_deploy_template
  before_script: 
   - ./script/utils/wait_on_job label='app:percona-deployment-cstor'
  script: 
   - ./script/apps/percona/workload/cstor/percona-app-workload-cstor

percona-cstor-run/load/check 2:3:
  extends: .app_deploy_template
  before_script: 
   - ./script/utils/wait_on_job label='app:percona-deployment-cstor'
  script: 
   - ./script/apps/percona/workload/cstor/percona-app-liveness-cstor

## Define job template for chaos jobs 

.chaos_test_template:
  image: atulabhi/kops:v8
  when: always 
  before_script: 
   - ./script/utils/cluster_health_check component='test-infra'
  after_script:
   - ./script/utils/cluster_health_check component='test-infra'
  artifacts:
    paths: 
      - aws-openebs/

repl-kill-{percona-jiva}:
  stage: NODE-DRAIN
  extends: .chaos_test_template #dependencies: percona-cstor
  script:
   - ./script/chaos/node-maintenance-via-drain

cleanup-aws:
  when: always
  image: atulabhi/kops:v8
  dependencies:
    - aws-cluster
  stage: CLUSTER-CLEANUP
  script: 
    - chmod 755 ./script/aws-cleanup
    - ./script/aws-cleanup
